export const randomPrompts = [
  "Design an armchair that resembles an avocado.",
  "Create a surrealist oil painting of a cat playing checkers, inspired by Salvador Dali.",
  "Design a ukiyo-e style artwork of teddy bears shopping for groceries in Japan.",
  "Paint a humanoid robot playing chess, in the style of Matisse.",
  "Create a digital artwork of a panda mad scientist mixing sparkling chemicals.",
  "Take a macro 35mm photograph of two mice in Hawaii, wearing tiny swimsuits and carrying surfboards.",
  "Create a 3D render of a cute tropical fish in an aquarium, set against a dark blue background.",
  "Design an astronaut lounging in a tropical resort in space, with a vaporwave aesthetic.",
  "Paint a portrait of a capybara wearing medieval royal robes and an ornate crown, set against a dark background.",
  "Create a stained glass window depicting a hamburger and french fries.",
  "Create a pencil and watercolor drawing of a futuristic city with flying cars.",
  "Design a sunlit indoor lounge area with clear and pastel pink pools, next to a big window.",
  "Create a digital artwork of a fortune-telling shiba inu reading your fate in a giant hamburger.",
  "Paint a sea otter with a pearl earring, inspired by Johannes Vermeer.",
  "Create an oil pastel drawing of an annoyed cat in a spaceship.",
  "Paint a fox in the style of Van Gogh's Starry Night.",
  "Knit a bowl of soup that looks like a monster.",
  "Create a plush toy robot sitting against a yellow wall.",
  "Design a synthwave style sunset above the reflecting water of the sea.",
  "Create a digital artwork of two futuristic towers with a skybridge covered in lush foliage.",
  "Create a 3D render of a rainbow colored hot air balloon flying above a reflective lake.",
  "Design a comic book cover of a superhero wearing headphones.",
  "Create a centered explosion of colorful powder on a black background.",
  "Take a photograph of a Samoyed dog with its tongue out hugging a white Siamese cat.",
  "Take a photograph of a white fur monster standing in a purple room.",
  "Create a digital artwork of Michelangelo's sculpture of David wearing headphones djing.",
  "Design a samurai riding a horse on Mars, with a lomography aesthetic.",
  "Take a 50mm photograph of a modern, sleek Cadillac driving along the Gardiner expressway with downtown Toronto in the background.",
  "Take a realistic photograph of a young woman with blue eyes and blonde hair.",
  "Design a man standing in front of a stargate to another dimension.",
  "Create a movie poster for Spongebob Squarepants in the Blair Witch Project.",
  "Design a velociraptor working at a hotdog stand, with a lomography aesthetic.",
  "Take a 50mm photograph of a man walking through the bustling streets of Kowloon at night, lit by many bright neon shop signs.",
  "Create an animated Pixar-style movie featuring a living BBQ.",
  "Design a futuristic cyborg dance club, with neon lights.",
  "Create a long-lost Star Wars 1990 Japanese Anime.",
  "Design a hamburger in the shape of a Rubik's cube, with professional food photography.",
  "Create a Blade Runner Cyberpunk-style synthwave hedgehog.",
  "Design an astronaut encountering an alien life form on a distant planet, with photography.",
  "Take a photograph of a dinosaur exploring Cape Town.",
  "A robot playing basketball on Mars",
  "A tropical island with a secret underwater city",
  "A haunted house with a friendly ghost",
  "A giant octopus attacking a city",
  "A space station orbiting a black hole",
  "A group of fairies having a tea party in a garden",
  "A futuristic city with flying cars and holographic billboards",
  "A magical unicorn with rainbow-colored fur",
  "A dragon sleeping in a cave full of treasure",
  "A superhero fighting a giant monster",
  "An underwater scene with colorful coral reefs and fish",
  "A city skyline at night with fireworks in the background",
  "A group of aliens having a dance party on a spaceship",
  "A forest scene with a majestic deer",
  "A time-traveling adventurer exploring ancient ruins",
  "A majestic eagle soaring over a mountain range",
  "A steampunk robot with mechanical arms",
  "A mermaid lounging on a rock in the ocean",
  "A mystical wizard casting a spell in a dark forest",
  "A space battle with laser beams and explosions",
  "A neon-lit cityscape with a giant robot looming in the background",
  "A herd of elephants grazing on a field of multicolored flowers",
  "A futuristic train station with hovertrains departing and arriving",
  "A surreal landscape with giant mushrooms and a small village in the distance",
  "An underwater city with schools of colorful fish swimming around the buildings",
  "A group of fairies having a tea party in a magical forest",
  "A city in the clouds with floating buildings and airships",
  "A dragon breathing fire on a medieval castle",
  "A robot repair shop with various robots waiting to be fixed",
  "A night scene with a glowing full moon and a lone wolf howling in the distance",
  "A floating city made entirely of candy, digital art",
  "A lion wearing a crown of flowers in a field of lavender, oil painting",
  "A futuristic robot bartender mixing a cocktail, 3D render",
  "A sunset over a desert landscape with a giant cactus, photography",
  "A dragon breathing fire into a night sky filled with stars, digital art",
  "A surrealistic landscape of a castle in the clouds, oil painting",
  "A hummingbird drinking nectar from a neon flower, digital art",
  "An underwater scene of a coral reef with a mermaid, digital art",
  "A portrait of a fox wearing a top hat and monocle, pencil drawing",
  "A steampunk flying machine soaring through the clouds, digital art",
  "A UFO abducting a cow in a rural landscape, digital art",
  "A retro sci-fi cityscape with flying cars, digital art",
  "A fantasy forest with giant mushrooms and a fairy, digital art",
  "A psychedelic kaleidoscope of colors and patterns, digital art",
  "A vintage pin-up girl riding a rocket, digital art",
  "A portrait of a robot with a human heart, digital art",
  "A surrealistic scene of a giant snail carrying a house on its back, oil painting",
  "A surreal landscape of floating islands, digital art",
  "A portrait of a mermaid lounging on a rock in a misty sea, oil painting",
  "A 3D render of a robot walking its dog in a futuristic cityscape",
  "An oil painting of a lion wearing a top hat and monocle, sitting in a library",
  "A photo of a hummingbird sipping nectar from a flower in mid-flight",
  "A portrait of a dragon queen sitting on a throne made of skulls, digital art",
  "A 3D render of a futuristic hoverbike speeding through a neon-lit city",
  "A painting of a penguin playing a grand piano in a snowy forest",
  "A photo of a magical forest with giant mushrooms and floating orbs",
  "An oil painting of a stormy sea with a lighthouse in the distance",
  "A 3D render of a sci-fi laboratory filled with glowing tubes and machinery",
  "A digital art piece of a cat riding a bicycle in a post-apocalyptic world",
  "A portrait of a robotic geisha in a traditional Japanese garden",
  "A photo of a sunset over a field of lavender in Provence, France",
  "A painting of a unicorn grazing in a field of rainbow-colored flowers",
  "A 3D render of a spaceship traveling through a wormhole",
  "An oil painting of a majestic elephant standing in a sun-drenched savanna",
  "A photo of a baby chameleon clinging to a twig with its tail",
  "A portrait of a cyborg samurai in a futuristic Tokyo skyline",
  "A 3D render of a neon-drenched alleyway in a cyberpunk city",
  "A painting of a phoenix rising from the ashes against a fiery background",
  "A photo of a waterfall cascading down a lush jungle cliff",
  "A portrait of a witch brewing potions in a mysterious forest, digital art",
  "A 3D render of a futuristic sports car racing through a tunnel",
  "An oil painting of a panda lounging in a bamboo forest",
  "A photo of a herd of wild horses running across a sunlit plain",
  "A painting of a dragonfly hovering over a pond with lily pads",
  "A 3D render of a futuristic underwater city with bioluminescent creatures",
  "A digital art piece of a magical castle floating in the clouds",
  "A portrait of a cybernetic tiger prowling in a neon-lit alleyway",
];

export function getRandomPrompt(prompt) {
  const randomIndex = Math.floor(Math.random() * randomPrompts.length);
  const randomPrompt = randomPrompts[randomIndex];

  if (randomPrompt === prompt) return getRandomPrompt(prompt);

  return randomPrompt;
}
