import React from "react";
import AliceCarousel from "react-alice-carousel";
import data from "./data";

function Carousel() {
  const items = data.map((item) => {
    return (
      <div className="flex space-x-5 items-center">
        <img
          src={item}
          alt="AI Art"
          className="px-2 cursor-pointer hover:scale-105 transition-all duration-300 ease-out"
        />
      </div>
    );
  });

  const responsive = {
    0: {
      items: 2,
    },
    512: {
      items: 4,
    },
    1024: {
      items: 6,
    },
  };

  return (
    <section className="py-14">
      <h2 className="text-2xl mx-2.5 font-semibold text-[#000] mb-8">
        Stunning images generated by PixelAI
      </h2>

      <AliceCarousel
        mouseTracking
        infinite
        autoPlayInterval={1000}
        animationDuration={1500}
        disableButtonsControls
        disableDotsControls
        responsive={responsive}
        autoPlay
        items={items}
      />
    </section>
  );
}

export default Carousel;
